language: php
php: 
    7.1        

before_script:
    - createdb testdb -U postgres
    - psql -f db/schema.sql --username=postgres testdb
    - psql -c '\connect testdb' -f db/fixtures.sql --username=postgres testdb 
    - composer self-update
    - composer install --no-interaction

services:
  - postgresql

script: phpunit --configuration phpunit_pgsql.xml --coverage-text

notifications:
    email: false
